FROM projectdiscovery/nuclei:v3.11.1 AS nuclei

FROM kali-linux-headless:2026.3.4

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends chromium \
 && rm -rf /var/lib/apt/lists/*

COPY --from=nuclei /usr/local/bin/nuclei /usr/local/bin/nuclei
